# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_gallery_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=12)),
                ('subject', models.CharField(max_length=64)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Catering Message',
                'verbose_name_plural': 'Catering Messages',
            },
        ),
    ]
