# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_catering'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catering',
            old_name='message',
            new_name='details',
        ),
    ]
