# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20170804_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
