# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0003_delete_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(default=True, max_length=254)),
                ('subject', models.CharField(max_length=64)),
                ('message', models.TimeField()),
            ],
        ),
    ]
