# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(),
        ),
    ]
